"""Add organizations and missing columns

Revision ID: 577ed01e3613
Revises: 0001
Create Date: 2026-08-14 17:00:55.212022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577ed01e3613'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('billing_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('developer_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_api_keys_organization_id'), 'developer_api_keys', ['organization_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_executions_job_id'), 'job_executions', ['job_id'], unique=False)
    op.add_column('repositories', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.alter_column('repositories', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_repo_owner_github'), 'repositories', type_='unique')
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_repo_org_github', 'repositories', ['organization_id', 'github_id'])
    op.create_foreign_key(None, 'repositories', 'organizations', ['organization_id'], ['id'])
    op.add_column('repository_versions', sa.Column('commit_sha', sa.String(), nullable=False))
    op.add_column('repository_versions', sa.Column('parent_commit_sha', sa.String(), nullable=True))
    op.create_unique_constraint('uq_repo_version_commit_sha', 'repository_versions', ['repository_id', 'commit_sha'])
    op.drop_column('repository_versions', 'commit_hash')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_versions', sa.Column('commit_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_repo_version_commit_sha', 'repository_versions', type_='unique')
    op.drop_column('repository_versions', 'parent_commit_sha')
    op.drop_column('repository_versions', 'commit_sha')
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_constraint('uq_repo_org_github', 'repositories', type_='unique')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.create_unique_constraint(op.f('uq_repo_owner_github'), 'repositories', ['owner_id', 'github_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('repositories', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('repositories', 'organization_id')
    op.drop_index(op.f('ix_job_executions_job_id'), table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_developer_api_keys_organization_id'), table_name='developer_api_keys')
    op.drop_table('developer_api_keys')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
